version: 2.1

jobs:
  test:
    docker:
      # image: cimg/python:3.8.4
      - image: openmodelica/openmodelica:v1.22.4-ompython

    working_directory: ~/project

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            apt install python3.10-venv
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - test